import React from 'react';
import { Play, Video, ArrowRight } from 'lucide-react';

interface ShowcaseCard {
  id: number;
  title: string;
  brand: string;
  category: string;
  aspect: string;
  gradient: string;
  accent: string;
}

const row1Cards: ShowcaseCard[] = [
  { id: 1, title: 'Air Max Future Motion', brand: 'Nike Campaign', category: 'Footwear', aspect: '9:16 Vertical', gradient: 'from-[#013F32] via-[#0b2b23] to-[#161616]', accent: '#E7FE25' },
  { id: 2, title: 'Serene Alpine Villa & Spa', brand: 'Aman Resorts', category: 'Hospitality', aspect: '9:16 Vertical', gradient: 'from-[#161616] via-[#013F32]/80 to-[#161616]', accent: '#FDFDFD' },
  { id: 3, title: 'Cyberpunk Surge Energy', brand: 'Volt Energy', category: 'Beverage', aspect: '9:16 Vertical', gradient: 'from-[#013F32] via-[#161616] to-[#013F32]', accent: '#E7FE25' },
  { id: 4, title: 'Automatic Tourbillon Watch', brand: 'Aethel Timepieces', category: 'Luxury', aspect: '9:16 Vertical', gradient: 'from-[#161616] via-[#1f1f1f] to-[#013F32]', accent: '#E7FE25' },
  { id: 5, title: 'Autumn Knitwear Lookbook', brand: 'Verve Studio', category: 'Fashion', aspect: '9:16 Vertical', gradient: 'from-[#013F32]/90 via-[#0a231c] to-[#161616]', accent: '#FDFDFD' },
  { id: 6, title: 'Hyper-EV Autonomous Drive', brand: 'Apex Motors', category: 'Automotive', aspect: '9:16 Vertical', gradient: 'from-[#161616] via-[#013F32]/70 to-[#161616]', accent: '#E7FE25' },
];

const row2Cards: ShowcaseCard[] = [
  { id: 7, title: 'Hydra Glow Renewal Serum', brand: 'Lumina Skin', category: 'Cosmetics', aspect: '9:16 Vertical', gradient: 'from-[#161616] via-[#013F32]/60 to-[#161616]', accent: '#E7FE25' },
  { id: 8, title: 'Artisan Espresso Alchemy', brand: 'Noir Coffee Co.', category: 'Dining', aspect: '9:16 Vertical', gradient: 'from-[#013F32] via-[#161616] to-[#013F32]', accent: '#FDFDFD' },
  { id: 9, title: 'AI Workspace Productivity', brand: 'SyncFlow Systems', category: 'Tech SaaS', aspect: '9:16 Vertical', gradient: 'from-[#161616] via-[#222] to-[#013F32]', accent: '#E7FE25' },
  { id: 10, title: 'Brutalist Villa Walkthrough', brand: 'ArchForm Studio', category: 'Real Estate', aspect: '9:16 Vertical', gradient: 'from-[#013F32]/80 via-[#0d2e25] to-[#161616]', accent: '#E7FE25' },
  { id: 11, title: 'Wireless Spatial Audio Pro', brand: 'Aura Sound', category: 'Electronics', aspect: '9:16 Vertical', gradient: 'from-[#161616] via-[#013F32]/90 to-[#161616]', accent: '#FDFDFD' },
  { id: 12, title: 'Seamless Compression Gear', brand: 'Zenith Performance', category: 'Athletics', aspect: '9:16 Vertical', gradient: 'from-[#013F32] via-[#08221b] to-[#161616]', accent: '#E7FE25' },
];

export const ShowcaseSection: React.FC = () => {
  // Triple arrays for seamless infinite looping marquee
  const marqueeRow1 = [...row1Cards, ...row1Cards, ...row1Cards];
  const marqueeRow2 = [...row2Cards, ...row2Cards, ...row2Cards];

  return (
    <section className="relative w-full bg-[#013F32] text-[#FDFDFD] py-24 sm:py-28 overflow-hidden select-none border-t border-[#013F32]/80">

      {/* Section Header */}
      <div className="max-w-7xl mx-auto px-6 sm:px-10 lg:px-12 mb-12 sm:mb-16">
        <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-6 pb-2 border-b border-white/10">
          <div className="space-y-3 max-w-xl">
            {/* Editorial Tag */}
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-[#161616]/80 border border-white/10 backdrop-blur-md shadow-sm font-sans-body">
              <span className="w-2 h-2 rounded-full bg-[#E7FE25] animate-pulse" />
              <span className="text-[#E7FE25] font-semibold uppercase tracking-wider text-[10px]">Curated Campaigns</span>
              <span className="text-white/20 text-xs">/</span>
              <span className="text-white/70 text-xs font-medium">Production Reel</span>
            </div>

            <h2 className="font-serif-display text-4xl sm:text-5xl md:text-6xl font-normal text-[#FDFDFD] tracking-tight">
              Our Work
            </h2>

            <p className="font-sans-body text-sm sm:text-base text-[#FDFDFD]/75 leading-relaxed font-normal">
              Explore commercial video campaigns generated by our multi-model AI pipeline across industries.
            </p>
          </div>

          {/* Action Button - Neatly aligned at the right side */}
          <div className="sm:pb-1">
            <button className="group inline-flex items-center gap-2.5 px-6 py-3 rounded-full bg-[#161616] hover:bg-[#E7FE25] hover:text-[#161616] text-[#FDFDFD] font-sans-body text-sm font-medium transition-all duration-300 shadow-xl border border-white/10 cursor-pointer active:scale-95 whitespace-nowrap">
              <span>Explore All Commercials</span>
              <ArrowRight className="w-4 h-4 text-[#E7FE25] group-hover:text-[#161616] group-hover:translate-x-1 transition-transform" />
            </button>
          </div>
        </div>
      </div>


      {/* Two Row Infinite Video Showcase Marquee (Mobile Screen 9:16 Aspect Ratio) */}
      <div className="space-y-8 overflow-hidden">

        {/* Row 1: Moves Left in Slow Motion */}
        <div className="relative w-full overflow-hidden">
          <div className="flex gap-6 w-max animate-marquee-left hover:[animation-play-state:paused]">
            {marqueeRow1.map((card, index) => (
              <div
                key={`row1-${card.id}-${index}`}
                className="group relative w-[240px] sm:w-[280px] md:w-[320px] lg:w-[340px] h-[426px] sm:h-[498px] md:h-[568px] lg:h-[604px] rounded-[32px] p-2 bg-gradient-to-b from-[#161616] via-[#013F32]/50 to-[#161616] border border-white/10 shadow-2xl transition-all duration-300 hover:scale-[1.03] hover:border-[#E7FE25] cursor-pointer flex-shrink-0"
              >
                {/* Inner Mobile Screen Canvas (9:16) */}
                <div className={`relative w-full h-full rounded-[22px] bg-gradient-to-br ${card.gradient} overflow-hidden flex flex-col justify-between p-4.5 border border-white/5`}>
                  {/* Subtle ambient lighting */}
                  <div className="absolute inset-0 bg-radial from-[#E7FE25]/10 via-transparent to-black/60 opacity-60 group-hover:opacity-90 transition-opacity" />

                  {/* Top Mobile Screen Notch / Badges */}
                  <div className="relative z-10 flex items-center justify-between">
                    <span className="text-[10px] font-semibold px-2.5 py-0.5 rounded-full bg-[#161616]/90 text-[#E7FE25] border border-[#E7FE25]/30 font-sans-body">
                      {card.category}
                    </span>
                    <span className="text-[10px] font-mono text-white/60 bg-black/60 px-2 py-0.5 rounded-full border border-white/5">
                      9:16
                    </span>
                  </div>

                  {/* Center Play Icon Placeholder */}
                  <div className="relative z-10 my-auto flex flex-col items-center justify-center gap-2.5">
                    <div className="w-14 h-14 rounded-2xl bg-[#161616]/85 border border-[#E7FE25]/50 flex items-center justify-center text-[#E7FE25] shadow-xl group-hover:scale-110 group-hover:bg-[#E7FE25] group-hover:text-[#161616] transition-all duration-300">
                      <Play className="w-6 h-6 ml-0.5 fill-current" />
                    </div>
                    <span className="text-[11px] font-medium text-white/70 group-hover:text-white transition-colors flex items-center gap-1.5 font-sans-body">
                      <Video className="w-3.5 h-3.5 text-[#E7FE25]" />
                      Video Slot
                    </span>
                  </div>

                  {/* Bottom Video Metadata */}
                  <div className="relative z-10 pt-3 border-t border-white/10 font-sans-body space-y-1 bg-gradient-to-t from-black/80 via-black/40 to-transparent -mx-4.5 -mb-4.5 p-4 rounded-b-[22px]">
                    <div className="text-xs sm:text-[13px] font-semibold text-white truncate leading-tight">{card.title}</div>
                    <div className="text-[11px] text-[#E7FE25] font-medium flex items-center justify-between">
                      <span>{card.brand}</span>
                      <span className="text-[9px] text-white/40 font-mono">4K • 60fps</span>
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Row 2: Moves Right in Slow Motion */}
        <div className="relative w-full overflow-hidden">
          <div className="flex gap-6 w-max animate-marquee-right hover:[animation-play-state:paused]">
            {marqueeRow2.map((card, index) => (
              <div
                key={`row2-${card.id}-${index}`}
                className="group relative w-[240px] sm:w-[280px] md:w-[320px] lg:w-[340px] h-[426px] sm:h-[498px] md:h-[568px] lg:h-[604px] rounded-[32px] p-2 bg-gradient-to-b from-[#161616] via-[#013F32]/50 to-[#161616] border border-white/10 shadow-2xl transition-all duration-300 hover:scale-[1.03] hover:border-[#E7FE25] cursor-pointer flex-shrink-0"
              >
                {/* Inner Mobile Screen Canvas (9:16) */}
                <div className={`relative w-full h-full rounded-[22px] bg-gradient-to-br ${card.gradient} overflow-hidden flex flex-col justify-between p-4.5 border border-white/5`}>
                  <div className="absolute inset-0 bg-radial from-[#E7FE25]/10 via-transparent to-black/60 opacity-60 group-hover:opacity-90 transition-opacity" />

                  {/* Top Mobile Screen Notch / Badges */}
                  <div className="relative z-10 flex items-center justify-between">
                    <span className="text-[10px] font-semibold px-2.5 py-0.5 rounded-full bg-[#161616]/90 text-[#E7FE25] border border-[#E7FE25]/30 font-sans-body">
                      {card.category}
                    </span>
                    <span className="text-[10px] font-mono text-white/60 bg-black/60 px-2 py-0.5 rounded-full border border-white/5">
                      9:16
                    </span>
                  </div>

                  {/* Center Play Icon Placeholder */}
                  <div className="relative z-10 my-auto flex flex-col items-center justify-center gap-2.5">
                    <div className="w-14 h-14 rounded-2xl bg-[#161616]/85 border border-[#E7FE25]/50 flex items-center justify-center text-[#E7FE25] shadow-xl group-hover:scale-110 group-hover:bg-[#E7FE25] group-hover:text-[#161616] transition-all duration-300">
                      <Play className="w-6 h-6 ml-0.5 fill-current" />
                    </div>
                    <span className="text-[11px] font-medium text-white/70 group-hover:text-white transition-colors flex items-center gap-1.5 font-sans-body">
                      <Video className="w-3.5 h-3.5 text-[#E7FE25]" />
                      Video Slot
                    </span>
                  </div>

                  {/* Bottom Video Metadata */}
                  <div className="relative z-10 pt-3 border-t border-white/10 font-sans-body space-y-1 bg-gradient-to-t from-black/80 via-black/40 to-transparent -mx-4.5 -mb-4.5 p-4 rounded-b-[22px]">
                    <div className="text-xs sm:text-[13px] font-semibold text-white truncate leading-tight">{card.title}</div>
                    <div className="text-[11px] text-[#E7FE25] font-medium flex items-center justify-between">
                      <span>{card.brand}</span>
                      <span className="text-[9px] text-white/40 font-mono">4K • 60fps</span>
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>

      </div>

    </section>
  );
};









