/**
 * Slice 10: Multi-Format & Multi-Platform Adaptation Constants
 */

export const ADAPTATION_PLATFORMS = {
  TIKTOK: 'TIKTOK',
  INSTAGRAM_REELS: 'INSTAGRAM_REELS',
  YOUTUBE_SHORTS: 'YOUTUBE_SHORTS',
  YOUTUBE_LANDSCAPE: 'YOUTUBE_LANDSCAPE',
  META_FEED: 'META_FEED',
};

export const SUPPORTED_PLATFORMS = Object.values(ADAPTATION_PLATFORMS);

export const ADAPTATION_STATUS = {
  PLANNED: 'PLANNED',
  ADAPTING: 'ADAPTING',
  VALIDATING: 'VALIDATING',
  RENDERING: 'RENDERING',
  EVALUATING: 'EVALUATING',
  APPROVED: 'APPROVED',
  WARNING: 'WARNING',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
};

export const VALID_STATUS_TRANSITIONS = {
  [ADAPTATION_STATUS.PLANNED]: [ADAPTATION_STATUS.ADAPTING, ADAPTATION_STATUS.RENDERING, ADAPTATION_STATUS.WARNING, ADAPTATION_STATUS.FAILED, ADAPTATION_STATUS.CANCELLED],
  [ADAPTATION_STATUS.ADAPTING]: [ADAPTATION_STATUS.VALIDATING, ADAPTATION_STATUS.RENDERING, ADAPTATION_STATUS.FAILED, ADAPTATION_STATUS.CANCELLED],
  [ADAPTATION_STATUS.VALIDATING]: [ADAPTATION_STATUS.RENDERING, ADAPTATION_STATUS.WARNING, ADAPTATION_STATUS.FAILED, ADAPTATION_STATUS.CANCELLED],
  [ADAPTATION_STATUS.RENDERING]: [ADAPTATION_STATUS.EVALUATING, ADAPTATION_STATUS.FAILED, ADAPTATION_STATUS.CANCELLED],
  [ADAPTATION_STATUS.EVALUATING]: [ADAPTATION_STATUS.APPROVED, ADAPTATION_STATUS.WARNING, ADAPTATION_STATUS.FAILED, ADAPTATION_STATUS.CANCELLED],
  [ADAPTATION_STATUS.WARNING]: [ADAPTATION_STATUS.ADAPTING, ADAPTATION_STATUS.RENDERING, ADAPTATION_STATUS.APPROVED, ADAPTATION_STATUS.FAILED, ADAPTATION_STATUS.CANCELLED],
  [ADAPTATION_STATUS.APPROVED]: [ADAPTATION_STATUS.ADAPTING, ADAPTATION_STATUS.RENDERING], // Re-adaptation allowed
  [ADAPTATION_STATUS.FAILED]: [ADAPTATION_STATUS.PLANNED, ADAPTATION_STATUS.ADAPTING, ADAPTATION_STATUS.RENDERING], // Retry allowed
  [ADAPTATION_STATUS.CANCELLED]: [],
};

export const CROP_STRATEGIES = {
  CENTER_CROP: 'CENTER_CROP',
  SMART_CROP: 'SMART_CROP',
  SUBJECT_AWARE_CROP: 'SUBJECT_AWARE_CROP',
  LETTERBOX: 'LETTERBOX',
  PILLARBOX: 'PILLARBOX',
  REPOSITION: 'REPOSITION',
  HYBRID: 'HYBRID',
};

export const DURATION_STRATEGIES = {
  TRIM_SCENE: 'TRIM_SCENE',
  COMPRESS_SCENE: 'COMPRESS_SCENE',
  REMOVE_OPTIONAL_SCENE: 'REMOVE_OPTIONAL_SCENE',
  RESEQUENCE_SCENE: 'RESEQUENCE_SCENE',
  PRESERVE_DURATION: 'PRESERVE_DURATION',
  REGENERATE_SCENE: 'REGENERATE_SCENE',
};

export const RESOURCE_LIMITS = {
  MAX_ADAPTATIONS_PER_REQUEST: 10,
  MAX_BULK_PLATFORMS: 5,
  MAX_TARGET_DURATION_SECONDS: 300,
  MAX_RENDER_RESOLUTION: 3840,
};
