"""add campaign strategy and creative concepts

Revision ID: 6b22628a72f6
Revises: 9dc5160e1a50
Create Date: 2026-08-17 20:40:54.810136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b22628a72f6'
down_revision: Union[str, Sequence[str], None] = '9dc5160e1a50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_strategies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('campaign_objective', sa.Text(), nullable=False),
    sa.Column('target_audience', sa.Text(), nullable=False),
    sa.Column('marketing_angle', sa.Text(), nullable=False),
    sa.Column('core_message', sa.Text(), nullable=False),
    sa.Column('call_to_action', sa.Text(), nullable=False),
    sa.Column('tone', sa.Text(), nullable=False),
    sa.Column('recommended_platform', sa.Text(), nullable=False),
    sa.Column('recommended_format', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id')
    )
    op.create_table('creative_concepts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('hook', sa.Text(), nullable=False),
    sa.Column('concept', sa.Text(), nullable=False),
    sa.Column('visual_direction', sa.Text(), nullable=False),
    sa.Column('emotional_direction', sa.Text(), nullable=False),
    sa.Column('call_to_action', sa.Text(), nullable=False),
    sa.Column('estimated_duration', sa.Integer(), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creative_concepts_campaign_id'), 'creative_concepts', ['campaign_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_creative_concepts_campaign_id'), table_name='creative_concepts')
    op.drop_table('creative_concepts')
    op.drop_table('campaign_strategies')
    # ### end Alembic commands ###
