"""create_storyboards_scenes_and_creative_bibles

Revision ID: 6cee1069971f
Revises: 6b22628a72f6
Create Date: 2026-08-17 20:53:24.866634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cee1069971f'
down_revision: Union[str, Sequence[str], None] = '6b22628a72f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storyboards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('aspect_ratio', sa.String(length=50), nullable=False),
    sa.Column('target_duration', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['concept_id'], ['creative_concepts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id')
    )
    op.create_table('creative_bibles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('storyboard_id', sa.UUID(), nullable=False),
    sa.Column('visual_style', sa.Text(), nullable=False),
    sa.Column('color_palette', sa.Text(), nullable=False),
    sa.Column('lighting_rules', sa.Text(), nullable=False),
    sa.Column('voiceover_profile', sa.Text(), nullable=False),
    sa.Column('music_sound_design', sa.Text(), nullable=False),
    sa.Column('negative_prompts', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['storyboard_id'], ['storyboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storyboard_id')
    )
    op.create_table('scenes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('storyboard_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('shot_type', sa.String(length=100), nullable=False),
    sa.Column('camera_movement', sa.String(length=100), nullable=False),
    sa.Column('visual_prompt', sa.Text(), nullable=False),
    sa.Column('audio_narration', sa.Text(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('lighting_atmosphere', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('video_asset_url', sa.String(length=500), nullable=True),
    sa.Column('audio_asset_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['storyboard_id'], ['storyboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenes_storyboard_id'), 'scenes', ['storyboard_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenes_storyboard_id'), table_name='scenes')
    op.drop_table('scenes')
    op.drop_table('creative_bibles')
    op.drop_table('storyboards')
    # ### end Alembic commands ###
